### ISSUE TITLE
好像没有args.update_pi这个参数

### ISSUE THREAD

**Issue by Wongcheukwai** [VITA-Group/Self-PU#1]
你好，
1.train.py的第347行的参数args.update_pi好像没定义，报错了，请问下这个参数的意思是什么？应该设为什么？
2.同样的问题还有在659行的args.turnoff_noisy, 请问是用来干嘛的？
3.def check_noisy(epoch):这个函数是用来干嘛的鸭？
4.357行的noisy_stop好像也没有定义，请问是用来干什么的鸭？
谢谢

**Comment by Ch4nYH** [comment]
谢谢你的问题。
问题1,2,4都是清理code时的遗留问题，我会清理掉；
问题3是用来检查noisy data是否启用的;
