### ISSUE TITLE
关于train_2s2t_mix和train_reweight_mix的问题

### ISSUE THREAD

**Issue by Wongcheukwai** [VITA-Group/Self-PU#2]
你好，

1. 我想问问train_2s2t_mix跟train_2s2t的区别是什么鸭？train_2s2t_mix对应于文中的哪个loss鸭？

2. 我想问问我跑了train_reweight_mix，但是报错说AttributeError: 'Namespace' object has no attribute 'flex'，请问一下flex这个是哪个参数 该怎么定呢？

谢谢你，我非常喜欢你的这篇icml和代码，我们也算同行了，目前正在赶ijcai，打算拿你这个做baseline ：)

**Comment by Ch4nYH** [comment]
您好,

1. mix的话是加上了self-calibrated training. 因为calibrate的计算过程比较慢，因此我们分成了两个scripts.
2. 这个也是清理code的时候的遗留, 我会将它删掉, 谢谢！
